server:
  port: 8383

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blackreading?useUnicode=true&charcterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.bk: debug

mybatis-plus:
  global-config:
    db-config:
      # 逻辑未删除
      logic-not-delete-value: 0
      # 逻辑删除
      logic-delete-field: 1
      # 逻辑删除对应字段
      logic-delete-value: delFlag
  # 扫描对应的文件包
  type-aliases-package: com.bk.*.entity
