server:
  port: 8383

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blackreading?useUnicode=true&charcterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost

